name: mapcss
version: 0.0.5
description: >
  mapcss provides an antlr based parser and a Dart framework for parsing
  and manipulating MapCSS stylesheets.
  MapCSS is used to define stylesheets for map rendering in the OpenStreetMap
  project, see http://wiki.openstreetmap.org/wiki/MapCSS. 
 
authors:
- Karl Guggisberg <karl.guggisberg@guggis.ch>
 
dependencies:
  unittest: any
  args: any
  js:
     # patched js-interop
     git:
        url: git://github.com/Gubaer/js-interop
        ref: function-proxy
        
  dartlr:
    git: 
      url: git://github.com/tiagomazzutti/dartlr.git
